### ISSUE TITLE
Request Feature: Remove Tag

### ISSUE THREAD

**Issue by WillemPieterse** [OskarZhang/TagListView#2]
Hi there!

Are you considering a "remove tag" feature?

**Comment by OskarZhang** [comment]
I never thought of it myself since it was not needed for my project but this sounds like an easy thing to implement. Would you like to see a remove method that deletes a label at an index?

**Comment by WillemPieterse** [comment]
Yes please! I think that would be much st effective :)

Sent from Outlook

On Wed, Nov 18, 2015 at 6:27 PM -0800, "Oskar Zhang" notifications@github.com wrote:

I never thought of it myself since it was not needed for my project but this sounds like an easy thing to implement. Would you like to see a remove method that deletes a label at an index?
